### ISSUE TITLE
网关节点增加入口，用于关联勾选/取消 网关各条分支上的节点

### ISSUE THREAD

**Issue by luofann** [TencentBlueKing/bk-sops#5814]
# 背景
1. 用户某些场景下，要重跑任务中的一些步骤，希望只执行部分步骤。当前平台只支持针对普通节点【选择/取消选择】

3. 当用户想要整体不执行网关各条分支上的节点时，需要挨个取消网关各个分支上所有的节点

5. 已经取消网关各个分支上所有的节点，网关节点依然展示在任务执行的画布中，且逻辑仍旧生效，
  条件表达式引用的变量仍然需要在执行时填写

![image](https://user-images.githubusercontent.com/42025090/203721793-af25e953-89f3-4702-a8e1-71003b90ac54.png)

![image](https://user-images.githubusercontent.com/42025090/203722049-a0c1a726-d051-4fc8-850c-c98e6ac0aa23.png)
![image](https://user-images.githubusercontent.com/42025090/203721549-660baf70-aafd-4d3c-9cb7-21e6dd21c9ce.png)

# 优化
### 在网关节点提供 快捷入口，用于关联 勾选/取消 网关各条分支上的节点
1. 网关上点击 「全选」、「不选」，能自动关联网关分支上的普通节点
   - 全选，点击时效果为全部勾选网关分支上的普通节点
   - 不选，点击时效果为取消勾选网关分支上的普通节点  

3. 网关各分支上节点被全部取消时，自动计算不再需要网关，任务执行时不展示网关，网关引用的变量归为「暂未使用的变量」

![image](https://user-images.githubusercontent.com/42025090/231411877-40dfcf9c-72c1-441a-b275-d8765f56eafb.png)

![image](https://user-images.githubusercontent.com/42025090/203748788-017b6d18-3546-4143-a8c8-ef7d24db5099.png)

**Comment by ywywZhou** [comment]
# 方案

理想情况下，所有分支的目标节点是同一个节点
1. 网关取消时先判断，该网关有多少条分支
2. 如果是1条，则自动关联对应的节点
3. 如果是多条，需要将网关id作为sourceId在树里面去递归查找targetId，再把所有的targetId当作sourceId去找对应的targetId，当每条分支的targetId相等时，代表这个网关的整体结束，需要把这个整体里面的所有节点全部取消选中

#问题

1. 当某条分支的目标节点是结束节点，是不是代表着跳过网关整体部分，直接连接结束节点

![image](https://user-images.githubusercontent.com/67539158/202416475-dca1b4dd-8920-45d4-b8af-f6ca2bf812d7.png)

**Comment by ecoli666** [comment]
### 并行网关&条件并行
- 取消并行网关和对应汇聚网关中间所有节点

### 分支网关
1. 所有分支连接汇聚：分支网关和对应汇聚网关中间所有节点
2. 有分支未连接汇聚
- 有分支连接到结束。从分支网关到结束的所有节点（相当于把结束当做汇聚）均被关联勾选/取消。
![image](https://user-images.githubusercontent.com/42025090/202661312-07d1ea4c-74fe-4a67-a4a5-24e8b23c5b06.png)
- 有分支连接到节点。从分支网关到此节点间的所有节点，不包含此节点（相当于把这个节点当做汇聚）均被关联勾选/取消。
![image](https://user-images.githubusercontent.com/42025090/202661998-fc8c3f19-3cbd-4cf4-9ab3-3f0f66a3d3b0.png)

### 规则：走任意一条分支都会经过的节点应该保留
