### ISSUE TITLE
JOB系列插件增加滚动执行及部分优化

### ISSUE THREAD

**Issue by ecoli666** [TencentBlueKing/bk-sops#5825]
现状
=======
### 功能缺失
1. `滚动执行` job分发文件和执行脚本新增了滚动执行能力，标准运维插件需要配套更新

     JOB的快速执行已增加“滚动执行”
![image](https://user-images.githubusercontent.com/42025090/178921189-8baa35f2-8308-4d43-a400-cd0a0d5eea34.png)

### 现存问题
![image](https://user-images.githubusercontent.com/42025090/195524105-873e32ae-722f-42a5-93c0-7994e8c4510a.png)

1. `是否允许跨业务`、`IP存在性校验`：公共团队希望将脚本、机器等资源提供给业务团队使用，而这些资源归属在公共团队自己的业务下。和业务团队所属的业务属于跨业务。此时job支持将**非业务**下的IP设置为白名单，满足跨业务执行、分发的诉求
    标准运维基于该场景提供了这2个选项，默认校验用户输入的IP是否在本业务下有效。非本业务IP需要关闭“`IP存在性校验”和开启“允许跨业务”。
    实际上对于执行目标，job本身已经有校验IP是否合法，标准运维直接透传给job即可，不需要额外校验

3. `IP tag分组`：根据job执行的结果对目标IP进行分组、但当前需要job任务执行成功才能获取分组信息。这没有必要。分组是job的原生能力，直接从job获取执行的分组结果（成功、失败、agent异常等）即可。另外也不需要做成选项，增加用户思考成本

4. `失败时提取变量`：用户使用<SOPS_VAR>v:helloworld</SOPS_VAR>语法在job中定义的输出变量，执行完后会从job日志中提取变量，提供给后续步骤使用。当前job节点执行失败时，默认不提取日志，需要开启此选项。这没有必要，直接做成默认的能力即可

5. `job成功历史`：标准运维上job节点执行失败时，用户可在job新创建一个任务，在标准运维录入新任务ID/选择新任务。用于获取任务中定义的输出变量给后续步骤使用。任务启动后应该是锁定的，不应该提供切换任务实例的入口给用户，直接移除。后续考虑添加支持管理员修改任务数据，用于处理紧急情况。

7. `快速分发文件 ` job快速分发文件插件，在分发多个源文件时，会产生多个job任务，与job行为不匹配

调整如下
=======

>  快速执行脚本、执行作业、业务集快速执行脚本、业务集执行作业

1. `job成功历史`：**直接移除**
3. `是否允许跨业务`、`IP存在性校验`： **直接移除**。
5. `IP tag分组`、 `失败时提取变量`：**移除选项，默认开启** 
7. 修改部分文案，和JOB对齐

> 快速执行脚本、业务集快速执行脚本 、快速分发文件、业务集快速分发文件  

- 增加滚动执行功能
![image](https://user-images.githubusercontent.com/42025090/195524498-130d48fa-0d74-476b-b30e-afec0c407b3b.png)

> 快速分发文件

- 优化文件分发插件逻辑，和job对齐

> 业务集相关插件
- 业务集ID，输入框改为下拉框，可支持搜索
![image](https://user-images.githubusercontent.com/42025090/195526167-dc9893e3-d2d3-432d-a26c-f3ae9316f720.png)

**Comment by hanshuaikang** [comment]
# Job插件改造方案

> 涉及到的插件

- 快速分发文件
  
- 业务集快速分发文件
  
- 快速执行脚本
  
- 业务集快速执行脚本
  

涉及到的改动:

- 快速分发文件, 业务集快速分发文件
  
  改动内容:
  

> 快速分发文件性能优化，支持多个源文件同时分发到某台主机上，减少调用次数
> 
> 新增滚动执行配置，新增三个字段，默认滚动执行为关闭状态。

    改动成本:

>    不涉及公共组件，主要改动execute函数。

- 快速执行脚本，业务集快速执行脚本
  
  改动内容:
  

> 去除IP存在性校验, IP Tag 分组, Job执行成功历史三个字段，其中IP存在性校验与Tag分组默认为True。
> 
> 新增滚动执行，策略表达式，滚动机制三个字段。

    改动成本:

> 涉及公共组件，GetJobHistoryResultMixin

需要注意的点，job执行成功历史只会在重试的时候展示。
