### ISSUE TITLE
【产品-无需评审会】查看模式下，增加不可编辑说明

### ISSUE THREAD

**Issue by ecoli666** [TencentBlueKing/bk-sops#5882]
### 查看模式下，右上角增加不可编辑说明
![image](https://user-images.githubusercontent.com/42025090/177244872-e7967404-1ae1-4c40-8856-1f913fc3d204.png)

**Comment by EchoQT** [comment]
不太认同。
查看模式下有查看的状态和相关可用操作，本来就和编辑态不一样，不需要什么说明文字吧？
另外，查看态和编辑态在界面上可以做一个大的识别度差异。

**Comment by ecoli666** [comment]
@EchoQT  
查看态和编辑态从识别度上来区分确实更合理。计划做如下优化
1：主界面增加辨识度区分
2：查看模式下，节点配置、变量配置等改为文本形式展示 。

当前查看模式是将表单只读禁用了，这是导致用户无法区分的重要原因
![image](https://user-images.githubusercontent.com/42025090/182285217-b7e88403-bb9f-4f67-922e-18c6eecf755d.png)

**Comment by EchoQT** [comment]
补充画布查看态的样式
