### ISSUE TITLE
标准运维任务控制管理端

### ISSUE THREAD

**Issue by normal-wls** [TencentBlueKing/bk-sops#5956]
## 背景

目前，标准运维的任务将很多操作的空间都交给用户，但是在问题排查和处理时，往往需要更多的一些数据和操作，才能保证对任务更好地控制和管理。

## 目标

1. 更新管理端适配新引擎
2. 增强管理端在任务上下文控制的操作功能

## 计划

1. 目前已有的管理端是基于v1引擎进行数据获取和设计，在全面切换v2引擎之后已经不可用。
    
    所以，需要针对v2引擎，更新实现对应的管理功能，并对一些已经将操作权限开放给用户的管理接口进行下线。
    
2. 支持在管理端进行任务上下文和节点输出变量的手动注入功能，让第三方系统一直失败且在标准运维勾选输出变量的情况能够得以继续执行。

**Comment by normal-wls** [comment]
# 影响范围

具有管理员权限的任务管理相关接口，用户层无感知

# 方案

1. 去掉已经弃用的相关接口，这些接口的相关功能已经在用户态可以进行查看或操作
    1. node/force_fail
    2. taskflow/node/history/log
2. 更新没有适配新引擎的接口
    1. taskflow/detail
    2. taskflow/node/detail
3. 增加新接口，支持在执行失败时，往任务上下文中注入对应的变量。
    1. 后端提供对应接口，在支持的任务状态下注入对应上下文变量，需要进行对应鉴权
    2. 前端增加对应按钮

**Comment by ecoli666** [comment]
### 前端变动如下
新增“注入全局变量”的入口
![image](https://user-images.githubusercontent.com/42025090/194746005-5c10194a-9acd-435f-b541-c82ac1bb602f.png)

点击可添加全局变量
![image](https://user-images.githubusercontent.com/42025090/194745893-c442a3dd-295c-428a-9636-a78e56844b24.png)

**Comment by normal-wls** [comment]
注入全局变量的表单添加一列类型，默认是字符串，暂时支持字符串和字典类型

**Comment by normal-wls** [comment]
在变量的key placeholder中添加示例提示："请出入变量的KEY，形如${log_outputs}"
注入全局变量新接口: admin/taskflow/upsert_context，post请求，json传参，形如:
{
    "task_id": 15242,
    "context": {
        "${inject_var}": "20",
        "${inject_dict}": {"a": "b"},
        "${inject_int}": 123
    }
}

**Comment by normal-wls** [comment]
相关接口前端处理逻辑：
1. 需要判断任务对应的引擎类型，依据taskflow接口中的engine_ver，admin/taskflow/detail，admin/taskflow/node/detail和admin/taskflow/node/history/log仅v1引擎的时候才调用，v2引擎仍然调用非管理端对应接口
2. 注入全局变量按钮仅在v2引擎时显示，调用admin/taskflow/upsert_context接口
