### ISSUE TITLE
标准运维IPV6改造

### ISSUE THREAD

**Issue by hanshuaikang** [TencentBlueKing/bk-sops#5958]
# IP V6 标准运维项目改造评估

现情况标准运维大多数插件针对于IP字段还是手动输入为主，考虑到未来很长一段时间可能面临IPV6+IPV4  混用的局面，对于标准运维之前的插件，在第一阶段采取用户ipV4+IPV6 混输的方案:

![](file:///Users/hanshu/Library/Application%20Support/marktext/images/2022-08-15-20-56-19-image.png?msec=1660568179696)

### CC 插件部分:

- 上交主机至资源池
  
- 主机加锁
  
- 主机解锁
  
- 批量修改主机属性
  
- 批量更新主机所属业务模块
  
- 按规则修改主机自定义属性
  
- 故障机替换
  
- 更新VIP/VPort
  
- 更新主机属性
  
- 跨业务转移主机
  
- 转移主机模块
  
- 转移主机至待回收模块
  
- 转移主机至故障机模块
  
- 转移主机至空闲机模块
  

### JOB 插件:

- 业务集快速分发文件
  
- 业务集快速执行脚本
  
- 分发本地文件
  
- 快速分发文件
  
- 快速执行脚本
  

### 节点管理:

- 插件操作
  
- 新建任务
  

## CC 涉及到的接口:

- list_biz_hosts_topo
  
- execute_dynamic_group
  
- get_business_host
  
- get_business_host_topo
  
- find_host_by_topo
  
- list_biz_hosts
  

### JOB 涉及到的接口:

- 使用 host_id_list 对接 ip_list

### 改造方案:

目前插件对于CC接口的使用主要有以下几种情况:
- 从用户输入的内容中提取IP - `get_ip_by_regex`
- 去CC查询该IP是否存在，IP校验逻辑
- 通过模块或者业务查询IP列表。
- 根据IP列表获取host_id 列表。

### 对于IP提取的逻辑:
修改所有插件的针对用户输入IP内容的处理，替换部分插件的`split`取列表的方式，改为更为通用的正则处理，对于get_ip_by_regex，针对IPV4 与IPV6 分别提取两次。由于IPV6的地址可压缩，就带来了非常多种的压缩表现方式，对于正则匹配出来的IPV6地址，需要经过ipv6地址二次验证和扩展的方式，需要对用户压缩的IPV6地址进行还原之后用于后续的匹配查询。最终确保提取之后对ip列表是可用的。

### 对于IP校验的逻辑:
CC JOB 插件存在大量判断IP在CMDB是否存在的逻辑，例如在`get_business_host_topo` 之类的方法中，需要增加对IPv6主机的条件过滤，因为`IPv4`与`IPV6`分别存在于两个不同的字段中，在这一步将ip列表分割成ipv4与ipv6两个列表，重新构造筛选条件。对于IPV6，可能会出现同一个ip多个host_id的情况，对于这部分情况，需要校验并抛出异常，也就是传了10个ip进去，却查到15条host信息。

### 对于IP列表获取的逻辑
对于获取IP的插件，之前有获取ip列表的接口，主要是job用的接口, 应当支持返回根据参数决定是否返回ip_list 或者 host_id_list。目前的方案是之前的ip列表函数不变，在实际调用job接口时根据情况进行转换处理。

### 对于旧版IP选择器的改造
对于IP选择器而言，最终渲染成ip列表的核心逻辑是不变的，ip列表交给插件内部来决定是否支持ipv6, 但是需要支持IPV6主机IP的校验, 以及IPV6 主机的获取，对于某些host而言，bk_inner_ip 可能为空，同时

##存在的问题
### 参数组装逻辑较为分散
以JOB为例，JOB插件比如快速分发文件，快速执行脚本，业务集快速分发文件等存在参数组装较为分散的逻辑。对此应当添加公共的转换基类去处理所有在ipv6下的 source_ip 和 target_server的转换逻辑。新增环境变量作为开关使用

**Comment by hanshuaikang** [comment]
提取转换方案:
![image](https://user-images.githubusercontent.com/33194175/187930286-599eef64-11c1-444c-9cbf-dd5307262003.png)

**Comment by hanshuaikang** [comment]
![image](https://user-images.githubusercontent.com/33194175/188354566-8730b9a5-bfbd-40fa-b631-86ce3514a241.png)

**Comment by normal-wls** [comment]
需要补充下旧版ip选择器的新设计原型 & 前后端接口交互开发方案

**Comment by ecoli666** [comment]
### 用户端交互优化
**目标**：针对执行目标为IP的流程节点，帮忙用户提前校验录入的IP正确性，以及检查IP状态

改造功能点：

1. 支持在配置节点时，校验录入IP的正确性，检查agent状态、IP是否重复（根据hostid，可选择唯一确定的资源）。同时不再允许IP和变量混输
<img width="848" alt="image" src="https://user-images.githubusercontent.com/42025090/188379875-5acd843c-a296-4adb-8414-00a4e7f77536.png">
<img width="801" alt="image" src="https://user-images.githubusercontent.com/42025090/188380227-ab37d8b5-44c0-4689-a34f-dc197c4a2a58.png">


2. 因完成节点配置后，IP状态可能发生变更，所以需要支持在查看节点配置时，实时查看IP的正确性，检查agent状态、IP是否重复
<img width="815" alt="image" src="https://user-images.githubusercontent.com/42025090/188380575-63001697-5e7c-4fe7-aa73-ddcf1dcec277.png">

3. 因插件表单的IP字段可能会【设置为变量】，所以需要支持在任务执行录入输入参数时，对应的输入参数可以校验录入IP的正确性，检查agent状态、IP是否重复（同配置节点时的能力）

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/42025090/188380793-cffe99f2-a536-4efe-ae58-669d0bc999a1.png">

4. IP选择器增加IPv6字段，以及对应的展示字段配置按钮

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/42025090/188381574-f7436308-8c72-4b36-a9b5-59db86ba872f.png">
