### ISSUE TITLE
【产品-无需评审会】标准运维内部非法操作的优化

### ISSUE THREAD

**Issue by ecoli666** [TencentBlueKing/bk-sops#6044]
# 背景
对于标准运维平台自身（非插件连接的外部系统）因后台校验、数据库约束等非法操作现象而触发的报错，期望以一种更优雅的形式展示给用户,给予用户更明确的引导方便用户自己解决问题

如删除流程时的报错。目前将标准运维平台内部定义的非法操作和第三方系统报错混合在一起，使用了相同的样式，不友好。
![image](https://user-images.githubusercontent.com/42025090/190607520-ade4ee2f-a0d0-4406-940c-12f77c768197.png)

### 优化
实际对于这一类型的操作，我们完全可以提供给用户更可读的形式，提供给明确的引导。

如流程因被引用，不可删除时，明确告知用户

<img width="449" alt="image" src="https://user-images.githubusercontent.com/42025090/209767220-70e17bd2-b902-4ab8-8629-5e26b3bcbb86.png">

<img width="450" alt="image" src="https://user-images.githubusercontent.com/42025090/209767117-df6ba8b1-641b-4ff1-b59e-02e537ac25f0.png">

**Comment by EchoQT** [comment]
ok
