### ISSUE TITLE
【产品-无需评审会】【画布快捷操作】支持拖动节点到连线上完成插入

### ISSUE THREAD

**Issue by ecoli666** [TencentBlueKing/bk-sops#6052]
# 背景
用户需要调整流程执行的顺序，将某个节点插入到另外一个位置，需要执行6步操作，如图中所示

![image](https://user-images.githubusercontent.com/42025090/190945697-3a4ff53b-dc25-42e3-ae18-560e71252ab7.png)

当前，用户需要执行如下操作
1. 删除【待插入节点】的左侧连线
2. 删除【待插入节点】的右侧连线
3. 删除待插入位置的连线
4. 将【待插入节点】移动到待插入位置
5. 将【待插入节点】与右侧节点连线
6. 将【待插入节点】与右侧节点连线

## 优化：实现两个步骤完成调整节点在流程中的位置

1. 支持将一个节点解除连线，变成孤立节点
![image](https://user-images.githubusercontent.com/42025090/220517845-48d41faf-e7e9-46c3-9d44-d87f3fd1f8fb.png)

2. 新增“复制节点”icon，可将一个节点复制为孤立节点。修正原复制节点的文案，修改为“复制并插入节点”
![image](https://user-images.githubusercontent.com/42025090/220517933-a6789244-e2a2-40b7-825a-6d642edfb7e4.png)

3. 支持把一个孤立节点拖到线上，直接完成节点的插入
移动节点到连线上时，当连线长度**足够容纳**一个节点时，出现引导交互(连线变色)，提示用户可插入
![image](https://user-images.githubusercontent.com/42025090/220518058-557e3de9-81fb-4bea-a596-4465e3dfd1f9.png)

4. 当连线重叠时，不可插入。因为此时无法确认插入到哪条连线

![image](https://user-images.githubusercontent.com/42025090/191890301-e8b30615-ba75-4541-97c5-15149dd301d0.png)

**Comment by ywywZhou** [comment]
连线是以svg图片形式呈现的，我可以判断出拖拽的孤立节点是否拖拽到线上。但是线可能为折线，这时只能判断出节点拖拽到svg图片上，没法确认是否拖拽到线上
![image](https://user-images.githubusercontent.com/67539158/191880853-32154692-5371-4841-98f0-742f44c66e36.png)

**Comment by EchoQT** [comment]
ok

**Comment by ecoli666** [comment]
和设计师、前端同学沟通后。稍微修改下交互
