### ISSUE TITLE
【产品-无需评审会】优化执行任务时的参数“说明”展示

### ISSUE THREAD

**Issue by ecoli666** [TencentBlueKing/bk-sops#6071]
# 背景
当前，标准运维针对变量提供了变量说明，用于辅助用户输入。但说明信息过于隐蔽，计划优化交互，将说明铺在参数的下方

![image](https://user-images.githubusercontent.com/42025090/191693128-9182c2a1-37d0-4f81-9c7b-2acc4729d2a2.png)

![image](https://user-images.githubusercontent.com/42025090/191693772-8143b032-3938-4ddc-982a-3b20fbd1960a.png)

**Comment by EchoQT** [comment]
ok
