### ISSUE TITLE
【产品-无需评审会】任务执行时，增加节点的历史执行时间展示

### ISSUE THREAD

**Issue by ecoli666** [TencentBlueKing/bk-sops#6077]
# 背景
在任务执行时，正在运行中的节点。当执行时间超过心里预期时，对于任务执行者希望判断是节点执行异常（例如第三方系统hang住），还是节点本身执行需要较长时间。当前需要跳转第三方系统去确认状态，需要查看历史任务该节点的执行时间等。
但对于任务执行人并非流程管理者时，他可能没有权限、也没有能力做这个判断。

### 计划提供如下功能：
节点执行时，hover节点提供执行时间展示。
- 展示当前**已运行**时长
- 展示**最近一次**执行时长
- 计算该节点**最近N次的平均执行时长**（次数可由平台管理员配置）
- 如历史数据>=5 ,则取最后5次；如历史数据 <5 次，则展示具体次数
- 历史数据统计允许一定的延后（期望**10分钟**内），展示统计的时间点

> 节点历史数据，根据节点nodeid追溯历史数据，不以节点名称为判断条件。
因此节点删除后创建的同名节点将没有历史数据

任务执行者，基于**历史的执行时长**信息判断节点执行状态，如当前时间与历史时间偏差较大可通知管理人员进行介入

![image](https://user-images.githubusercontent.com/42025090/195753328-db1b7360-34a1-48e5-99f5-22c531a8489a.png)

**Comment by EchoQT** [comment]
ok

**Comment by normal-wls** [comment]
<h1>影响范围</h1>
<p>任务详情页面查看</p>
<p>任务详情api返回信息</p>
<h1>方案</h1>
<p>通过周期任务，每天在特定时间，将当天执行的任务进行批处理，计算出【已完成】的任务对应流程中的各个节点的执行时间，并进行聚合。</p>
<ol>
<li>
<p>建立统计表：</p>


列名 | 属性 | 备注
-- | -- | --
template_id | int |  
template_source | char |  
project_id | int |  
execution_time | dict | key为节点id，value为节点相关统计信息，如统计任务数、平均执行时间等


</li>
<li>
<p>节点关系映射：</p>
<p>目前在从模版创建任务的过程中，节点id会进行替换，所以任务节点id和模版id无法直接对应，当前只能通过节点名称来进行对应。</p>
<p>如果后续希望进行精确对应，计划在编辑流程过程中，对新节点添加一个template_node_id的字段，由前端生成uuid，该字段会一直传递到任务中，不同任务的相同节点也会拥有相同的id。</p>
</li>
<li>
<p>更新方式：</p>
<ol>
<li>获取当天【已完成】的所有任务</li>
<li>对于每一个任务：
<ol>
<li>获取任务中所有节点的执行详情</li>
<li>创建/更新统计表中对应template的统计数据</li>
</ol>
</li>
</ol>
</li>
<li>
<p>api改动：</p>
<ol>
<li>对于任务详情页面，提供新接口，用于查询当前任务所有节点的时间评估数据，在页面通过template_node_id进行匹配和展示。</li>
<li>对于任务详情相关api，则在存在template_node_id的情况下，将时间评估数据一同进行返回。</li>
</ol>
</li>
</ol>
<h1>讨论</h1>
<ul>
<li>对于无评估数据或数据不足情况的交互方式。</li>
<li>对于方案中的步骤2，如果要对现有数据直接生效，则可以用节点名称代替步骤2中的模版节点id。但是，当模版中存在多个同名节点时，会造成预测结果不准确，需要进行取舍。如果使用名字作为id，则需要说明计算不准确的情况和原因；如果使用新的template_node_id，则需要说明旧流程数据无法预测的原因，需要在交互上体现。</li>
</ul>

**Comment by normal-wls** [comment]
新增接口api/v3/taskflow/node_execution_record供查询，参数&返回可通过swagger ui查看
