### ISSUE TITLE
【产品-无需评审会】公共流程增加空间管理

### ISSUE THREAD

**Issue by ecoli666** [TencentBlueKing/bk-sops#6092]
背景
=======

目前，公共流程的管理模式非常类似于一个业务下的流程管理：所有公共流程共享这个业务空间。
有权限的用户在此空间下，使用**个人账号**创建自己的流程，或者申请已有流程的权限来协同管理。
管理基于流程的粒度，通过权限的控制实现了同一空间下自行治理各自的资源。

# 问题

### 管理问题
1. 没有空间墙，所有的流程都混在一起，缺乏分层管理。
   **公共流程的管理者** 只能以流程的粒度来管理资源。无法以一个统一空间的维度去管理维护，例如设置统一的管理人员。
2. 目前管理者是以 **个人** 身份在管理公共流程，但我们希望管理者以 **职能** 来管理公共流程。
   以职能来管理，这样可以随时添加/删除成员，移交管理权。
3. 当前有协同管理诉求时只能按流程粒度去申请权限，无法一篮子申请，比较繁琐。
   另外新增流程也无法直接获得权限，还需要重新申请

### 使用问题
1.  **公共流程的使用方** 无法快速定位目标流程，当前只能强依赖流程的名称去定位。

# 方案：为公共流程添加空间管理能力
1. 公共流程以空间的维度组织， 所有操作均下移至“空间”内，流程的新增/编辑/删除/查看 都在“空间”下完成
2. 创建空间自动创建 **分级管理员**，分级管理员下自动创建 空间管理者（成员包含创建者）、空间访问者 两个用户组
3. 协同管理者可申请加入对应的用户组，也可由现有空间管理者主动授权

![image](https://user-images.githubusercontent.com/42025090/228783672-4bf7c638-f5b6-4306-b141-b7e86f7afa56.png)

4. **存量流程**全部划分到系统内置的**默认空间**内，按照现存的流程粒度鉴权，不允许新增流程
5. 所有空间共享标签，空间者管理员或存量流程管理者 可创建标签和使用存量标签，**不可修改和删除**标签

### 流程图

![image](https://user-images.githubusercontent.com/42025090/228777331-3bcd7c97-28b5-4e86-b6f1-d9532cd7e059.png)

### 原型

1. 点击「公共流程管理」入口
- 默认选择 **最近访问** 空间
   - 最近访问空间为 **默认空间**，保持现有鉴权逻辑不变（判断是否有存量流程的新建、管理权限）
   - 最近访问空间非默认空间， 鉴权资源对象为「空间」
   
- 首次进入，无“最近访问空间”，选择任意有权限的空间
- 以上均无，跳转新的权限申请界面

![image](https://user-images.githubusercontent.com/42025090/228727204-5b32cb39-8e5c-4cd0-b4f2-4925a69e1221.png)

2. 新建空间，成功新建后，直接跳转对应空间

![image](https://user-images.githubusercontent.com/42025090/228782423-81d5e57a-0093-4106-b458-a55ece6c967b.png)

3. 使用空间

   - 新增为公共流程配置标签和新建标签
   - **默认空间**下，可转移流程到任意空间
   - 其它空间仅允许转移流程到**非默认空间**   
   - 转移流程需要有目标空间的「使用空间」权限

![image](https://user-images.githubusercontent.com/42025090/195591245-60c36946-e5ae-487d-aed2-ae523945c507.png)

![image-20221011170537273](https://user-images.githubusercontent.com/42025090/195051166-0c1df9ea-8711-4a9f-abb3-0e0cee65183e.png)

4. 管理空间
- 右上角空间列表可切换至其它空间和新建空间，空间列表展示所有空间，无权限空间带锁
- 点击管理空间按钮
   - 空间名称
   - 空间ID，**不可更改**
   - 空间管理者 ，对应IAM **空间管理者** 分组
   - 空间访问者，对应IAM **空间访问者** 分组
   - 空间说明

![image](https://user-images.githubusercontent.com/42025090/228782458-9db9c0b4-873f-42c6-84d6-d101ac3094a2.png)

7. 消费空间下的流程
     在项目下，直接列表展示**所有空间**下的公共流程，可按标签筛选流程
![image](https://user-images.githubusercontent.com/42025090/217144298-2015cf34-c168-4b6c-9a37-e84b45631fdc.png)

**Comment by EchoQT** [comment]
ok

**Comment by EchoQT** [comment]
空间管理功能缺失，包括基本信息、管理员管理等等。
新建公共流程的页面也缺失相关设计。

**Comment by ecoli666** [comment]
> 空间管理功能缺失，包括基本信息、管理员管理等等。 新建公共流程的页面也缺失相关设计。

1. 已补充空间管理功能
2. 要成为空间管理员，需要用户在权限中心**按照空间申请**管理权限，由空间当前管理员之一完成审批，不支持反向授权。从而保证所有鉴权操作都走权限中心。
3. 增加空间后，公共流程以空间的维度组织， 所有操作均下移至“空间”内，如流程的新增/编辑/删除/查询都在“空间”下完成
新建公共流程的页面和没有“空间”以前并无差异，所以没有特别设计。

**Comment by EchoQT** [comment]
补充的功能没看到原型？
另外，与权限系统协同不意味着不能做主动授权功能。具体方案可以和edwin讨论一下。

**Comment by ecoli666** [comment]
> 补充的功能没看到原型？ 另外，与权限系统协同不意味着不能做主动授权功能。具体方案可以和edwin讨论一下。

已和edwin沟通。可调用权限中心接口进行主动授权，并重新补充了“空间管理”的原型

**Comment by EchoQT** [comment]
ok
