### ISSUE TITLE
子流程输入参数更新数据后，父流程“设置为变量”生成的变量数据未更新

### ISSUE THREAD

**Issue by ecoli666** [TencentBlueKing/bk-sops#6094]
问题描述
=======
1. 子流程的下拉框变量配置了三个选项【A、B、C】，父流程中引用该子流程，该变量作为输入参数可由父流程传入。

![image](https://user-images.githubusercontent.com/42025090/192544957-31f9a705-16fa-4e17-92cf-28646e1ff031.png)

2. 将输入参数“设置为变量”，可以看到在父流程中生成了一个“组件变量”数据也为【A、B、C】
![image](https://user-images.githubusercontent.com/42025090/192544644-9695ca4f-e453-4446-8756-6703de460688.png)

3. 更新子流程下拉框的数据，可以看到新增了一个选项【D】
![image](https://user-images.githubusercontent.com/42025090/192546080-e60c790b-4e38-4a1e-ada9-6506839ddb2f.png)

4. 在父流程中更新子流程
![image](https://user-images.githubusercontent.com/42025090/192545900-a698639c-46c1-45ff-9239-5a33b1659369.png)

5. 但此时父流程中的变量还是旧数据，缺失了新增的选项【D】
![image](https://user-images.githubusercontent.com/42025090/192546499-fef26bfa-3475-4928-99a1-ee7bc6d63449.png)

**Comment by ywywZhou** [comment]
![image](https://user-images.githubusercontent.com/67539158/194743132-1c6d8c8f-5777-41e4-94be-1fbdd536d570.png)
