### ISSUE TITLE
【产品-无需评审会】第三方插件支持按分类组织

### ISSUE THREAD

**Issue by ecoli666** [TencentBlueKing/bk-sops#6222]
背景
=======
标准运维存在有两类插件
1. `内置插件`，内置在标准运维代码里，发布插件需要发布新版本
2. `第三方插件`，依托Paas，在Paas上部署和发布新版本，和标准运维解耦

当前，已按照平台维度对`内置插件`进行了分类组织和展示

![image](https://user-images.githubusercontent.com/42025090/198207435-443833c9-c76a-414f-9e9f-2f7e30637ba2.png)

`第三方插件`依托于Paas平台，之前PaaS缺失相关分类的字段，所有的插件是平铺展示,混在一起的，体验不好。

![image](https://user-images.githubusercontent.com/42025090/198208544-94645a84-7bcc-4a49-a25c-ee6405879c4b.png)

# 优化
当前，Paas已支持**插件开发者选择 管理员预定义的分类**

![image](https://user-images.githubusercontent.com/42025090/198211882-b13b9d62-e673-4ef9-bbd7-5bd8550920d1.png)

所以，希望**统一内置插件和第三方插件的展示**，为第三方插件也添加**按分类组织**的功能。
后续PaaS提供标签能力后，还可为第三方插件打上标签

![image](https://user-images.githubusercontent.com/42025090/198214774-51385a0b-6441-418e-9f16-4764cd479459.png)

**Comment by EchoQT** [comment]
ok

**Comment by normal-wls** [comment]
前端调用：
1. 通过/plugin_service/tags/接口获取所有分类数据，展示分类列表，默认用第一个分类id来过滤插件列表
2. 插件列表增加一个过滤条件：&tag={tag_id}，可以将插件通过tag进行分类
