### ISSUE TITLE
节点重试时结束时间显示错误问题

### ISSUE THREAD

**Issue by normal-wls** [TencentBlueKing/bk-sops#6237]

**Comment by guanjianqiang0408** [comment]
![企业微信截图_16673587924016](https://user-images.githubusercontent.com/103730408/199386920-a89d012c-f79f-448f-9bf1-8326676e555d.png)
需要修改eri.models.runtime.State中的archived_time获取逻辑，增加上状态判断如果为RUNNING就不应该有归档时间

**Comment by guanjianqiang0408** [comment]
修改后测试结果示例：
暂停后重试
![image](https://user-images.githubusercontent.com/103730408/199388376-c3ced53c-452c-4646-8fe4-f9691595aca9.png)
重试后强制失败
![image](https://user-images.githubusercontent.com/103730408/199388442-1475f371-543a-4c0c-bb15-173e7c438891.png)

**Comment by guanjianqiang0408** [comment]
![企业微信截图_16673619023732](https://user-images.githubusercontent.com/103730408/199411793-3da2d9b6-2b6c-4a15-8763-5fe916727700.png)
修改bamboo_engine引擎包内容，暂停任务重试时，允许重置archive_time属性
