### ISSUE TITLE
搜索字段需要与列表的字段名保持一致

### ISSUE THREAD

**Issue by ecoli666** [TencentBlueKing/bk-sops#6373]
问题
=======
搜索框里的搜索字段需要与列表的字段名保持一致

![image](https://user-images.githubusercontent.com/42025090/204689738-1f965d61-f25c-4afd-9956-1ebb4f62cff3.png)

**Comment by ywywZhou** [comment]
d1409408d7da1f2fdd153124ec2b429f2f457e5c
