### ISSUE TITLE
优化hover节点时的气泡卡片展示

### ISSUE THREAD

**Issue by ecoli666** [TencentBlueKing/bk-sops#6400]
# 问题
![企业微信截图_16702920761907](https://user-images.githubusercontent.com/42025090/205805332-67d05ef1-d9c9-40a9-8da5-e19ff26dc122.png)
1. 卡片样式不统一
2. 遮挡了按钮
3. 卡片hover移出效果不统一

# 优化
1. 单卡片，多卡片展示效果
<img width="1523" alt="企业微信截图_eaea70da-7767-4103-9aae-e9c473964020" src="https://user-images.githubusercontent.com/42025090/205804873-82854e1f-d5ae-4b49-bde6-ebe4730d4ea9.png">

2. 统一hover交互，移出时卡片消失

**Comment by ywywZhou** [comment]
6c4ae78e9df2ee0ec54ea3a0e013fdd33780d54e
