### ISSUE TITLE
业务选择框改造

### ISSUE THREAD

**Issue by ecoli666** [TencentBlueKing/bk-sops#6402]
改造点
=======

1. 全量显示所有业务，没有权限的显示在最后，按照字母序 a-z 排序
2. Hover 时，出现收藏的图标，收藏后，置顶收藏项
3. 对于收藏的业务，可以再次点击取消收藏，对于无权限的业务，点击后弹出申请弹窗
4. 业务的搜索需支持中英文关键字搜索
    
     ![image](https://user-images.githubusercontent.com/42025090/208572436-d95214e4-9aa2-4f3f-b3fe-63c0c74d079f.png)

6. 业务只支持单选

![image](https://user-images.githubusercontent.com/42025090/205856848-143a7882-d823-4d4d-bea5-0af6b4ede286.png)

**Comment by normal-wls** [comment]
1. user_project get接口返回增加两个字段：is_fav标识是否是收藏，is_user_project标识是否是用户有权限的业务
2. user_project 增加 favor&cancel_favor 两个接口，分别表示收藏项目和取消收藏项目，详见swagger ui
![image](https://user-images.githubusercontent.com/9864577/209774779-e8111d9c-e765-4a78-b5a0-fe438f5825a6.png)
