### ISSUE TITLE
【产品-无需评审会】任务列表点击优化&新建任务交互优化

### ISSUE THREAD

**Issue by ecoli666** [TencentBlueKing/bk-sops#6567]
现状
=======
流程有 手动 / API/ 定时 等多种执行方式

其中 手动 / API  又可以分成两种类型  常规任务 / 职能化任务

「职能化任务」在任务之上额外包装了一层，提供将任务交付第三方团队执行，且允许第三方团队以团队视图查看认领的任务列表

任务列表作为底层基本场景，无论是何种任务类型，底层形态应该是一致的

当前将底层场景和上层场景混扎在一起，想当混乱

### 问题表现
1. 常规任务，点击进入**任务详情**

![image](https://user-images.githubusercontent.com/42025090/220045701-07954062-7a10-453e-8839-0756f878b83a.png)

2. 职能化任务，点击进入**认领界面**
   
![image](https://user-images.githubusercontent.com/42025090/220046803-dd21f8cd-c2ff-4ef6-88eb-37d0c371bad6.png)

#### 一：切分场景
1. 底层场景的任务列表，不应该掺杂上层职能化场景的元素，任务列表统一路由到任务详情页
2. 任务列表新增 **任务类型** 字段 ，取值 【常规、职能化】
3. 职能化任务，修改 **未认领不可启动** 的约束，对于   **未认领** 的职能化任务，
    -  仅 任务创建人 可以点击 执行，并弹窗二次确认，确认执行后将任务类型更新为 **常规**，并从职能化列表删除
    -  非 任务创建人 ，禁用 「执行」按钮 。hover 文案 “未认领的职能化任务不允许执行”

4. 任务列表 **创建方式** 字段，更名为 **执行方式**

#### 二：新建任务交互优化
1. 流程类型 ，文案调整为 **任务类型**   
    - 常规
    - 职能化

######  **常规** 任务
1. 步骤条和按钮，调整文案，新建常规任务分 3 步
    - 选择节点
    - 填写参数
    - 去执行
    
![image](https://user-images.githubusercontent.com/42025090/227910732-1ce3155c-8ff9-4db4-9b0a-c52a1f35e3a0.png)

##### **职能化** 任务
1. 新建职能化任务分 5 步骤
    - 选择节点
    - 填写参数
    - 提交职能化 ，点击「提交职能化」后直接进入任务详情页，并提示 “提交成功，请通知职能化人员认领”
    - 职能化认领
    - 去执行

2. 职能化TAB下的任务列表，根据任务阶段，路由到不同页面
    - 未认领，进入认领页面
    - 已认领，进入任务详情页
    
3. 职能化任务列表，字段「认领状态」更名为 「任务阶段」
    - 未认领
    - 已认领
    - 已执行 / zhangsan
    - 已完成
 
#####  职能化TAB内新建任务
1. 直接创建 **职能化** 的任务,无需选择 **任务类型**
2. 新建职能化任务分 5 步骤
    - 选择节点
    - 填写参数
    - 提交职能化 ，点击「提交职能化」后直接进入 认领 页面
    - 职能化认领
    - 去执行
   
![image](https://user-images.githubusercontent.com/42025090/227915116-e4e2d971-05c5-4d1d-9dbf-b898e9d7c79b.png)

**Comment by EchoQT** [comment]
不ok，任务管理是底层基本场景，而任务是否给第三方授权是任务执行的一种上层场景。一个任务的执行方式并非只能在职能化或普通之间二选一。基于这几点重新思考一下，补全相关的交互说明。
