### ISSUE TITLE
【hawk】查看失败的流程节点接口异常

### ISSUE THREAD

**Issue by MarinPeng** [TencentBlueKing/bk-sops#6629]
关键信息
=======

- [ ] bk-sops 版本：

问题描述
=======

![企业微信截图_16784340979059](https://user-images.githubusercontent.com/50908315/224273200-2cd9c782-bb66-4ce2-9dd8-a1e3cfaca0dd.png)

重现方法
=======

**Comment by normal-wls** [comment]
对应节点中尝试渲染变量失败，符合预期。
