### ISSUE TITLE
cmdb把业务彻底删除，标准运维中仍可以选择到对应业务

### ISSUE THREAD

**Issue by liuliaozhong** [TencentBlueKing/bk-sops#6669]
关键信息
=======

- [ ] bk-sops 版本：3.9.14，3.17.3，3.25.12多个版本都能复现

问题描述
=======
cmdb业务彻底删除，标准运维中仍可以选择到对应业务

重现方法
1. 在cmdb中，把业务归档，在已归档业务中点彻底删除，
![image](https://user-images.githubusercontent.com/120009833/228816594-61ab68c2-34a9-4de7-9402-d11d6391cf70.png)

2. 标准运维中还可以选到，一直都还可以选 
![image](https://user-images.githubusercontent.com/120009833/228816741-96ab07e7-c5c7-4ae4-9827-06b209c1df71.png)

**Comment by ZhuoZhuoCrayon** [comment]
开发方案

* 问题定位：删除的业务没有在项目同步逻辑（gcloud/core/project.py sync_projects_from_cmdb）进行相应的停用/删除操作

* 如何处理：对比当前拉取的业务列表与项目（from_cmdb=true）的差异，将多出来的项目进行删除/停用
