### ISSUE TITLE
任务画布和状态API 标识跳过与重试次数

### ISSUE THREAD

**Issue by zyxazhang** [TencentBlueKing/bk-sops#6750]
问题描述
=======
1. 任务执行时，画布标识了节点是否配置了重试、跳过。但执行阶段用户更关心的是基于配置产生的行为，例如自动重试了N次 和  采用何种方式跳过。而配置是流程管理者设定了，执行者无法干预，有地方能够看到配置即可

2. 配置了自动重试的节点，在重试间隔期，任务不应该是 ”失败“状态。因为节点的执行并没有完结，并非静止的状态
    假设用户基于这个”失败“状态做一些处理，那么这种处理会和自动重试动作**产生冲突**

<img width="902" alt="image" src="https://github.com/TencentBlueKing/bk-sops/assets/42025090/25655676-73c2-493f-a466-d889dbc815a9">

优化
=======

### 画布优化
1. 移除节点失败处理选项展示
2. 在画布上增加手动重试和自动重试的次数，分开展示次数
3. 区分“自动跳过”和“手动跳过”

![image](https://github.com/TencentBlueKing/bk-sops/assets/86033636/c9eaa0e8-3227-4e54-b2df-d083dc29c576)

### 节点详情优化
1. 增加 **失败** 状态下的补充说明 ，补充重试次数
![image](https://github.com/TencentBlueKing/bk-sops/assets/42025090/0d237832-81ba-49ff-afe2-3ea49ebf5ce2)

### 任务状态API优化
1. 增加一个字段，用于判断Failed的任务是否处于真正静止状态 （即已达到最大自动重试次数）

**Comment by zyxazhang** [comment]
在taskflow/task_id接口中返回 running_count 这个对象字段，字段内容为
![image](https://github.com/TencentBlueKing/bk-sops/assets/86033636/a8355a22-7fe6-4925-860f-7739ce9b54a5)

**Comment by ZhuoZhuoCrayon** [comment]
## 联调信息

### taskflow/api/status/xx/?instance_id=xxx

增加 `auto_retry_infos`

![企业微信截图_8306ac5b-09ea-4080-b984-dfddf0c46cc8](https://github.com/TencentBlueKing/bk-sops/assets/42019787/40a7923c-66b9-4c11-986e-8a7da42e4144)

### taskflow/api/node/detail/ 

增加 `auto_retry_info`

![企业微信截图_151cd9f1-011a-41bd-bd68-093ddbbb7802](https://github.com/TencentBlueKing/bk-sops/assets/42019787/5746f9cc-f033-4d1a-9816-3917c1e06675)

手动重试次数 = 节点重试总数(`retry`) - 自动重试次数(`auto_retry_info.auto_retry_times`)
