### ISSUE TITLE
独立子流程任务失败后没有发送对应通知

### ISSUE THREAD

**Issue by MarinPeng** [TencentBlueKing/bk-sops#6888]
关键信息
=======

- [ ] bk-sops 版本：

问题描述
=======

重现方法
=======

**Comment by ecoli666** [comment]
@normal-wls 
子流程被引用时，父流程引用的仅是子流程的逻辑部分（进入版本快照的那部分数据，只有这部分数据变更会提示父流程更新）。所以被作为子流程节点时：

1. 忽略通知设置
2. 忽略执行代理人、任务偏好设置
