### ISSUE TITLE
提交职能化任务时，添加复制认领链接的路径

### ISSUE THREAD

**Issue by ecoli666** [TencentBlueKing/bk-sops#6901]
关键信息
=======

- [ ] bk-sops 版本：

用户期望
=======
运维新建任务提交职能化后，复制链接给职能化团队认领。
发现链接点进去不能执行，还要跑到职能化找到这个任务认领，有些麻烦

![image](https://github.com/TencentBlueKing/bk-sops/assets/42025090/d3a84b0b-838e-494a-8703-b53204be3340)

![image](https://github.com/TencentBlueKing/bk-sops/assets/42025090/3d1ef887-c65d-4806-8f28-73a30c41a8e4)

解决方案
=======
1. 提交职能化后，添加 **复制认领链接** 路径
2. message改成alert ，不自动消失
![image](https://github.com/TencentBlueKing/bk-sops/assets/42025090/c95eaeaa-1774-44e1-b2f8-e1af41f81f77)

**Comment by ywywZhou** [comment]
https://github.com/TencentBlueKing/bk-sops/pull/6920/commits/360cd6ec16044c257a0e65f9f19b3bcec096ed2c
