### ISSUE TITLE
作业平台系列插件，目标主机只有IPv6地址不展示，也不传给作业平台执行

### ISSUE THREAD

**Issue by liuliaozhong** [TencentBlueKing/bk-sops#7033]
关键信息
=======

- [ ] bk-sops 版本：3.28

问题描述
=======

1、作业平台系列插件，节点详情中输入目标服务器只展示了IPv4地址，IPv6地址没展示展示
![image](https://github.com/TencentBlueKing/bk-sops/assets/120009833/54805518-3cc4-467c-a4ba-eb87829e194e)
![image](https://github.com/TencentBlueKing/bk-sops/assets/120009833/1e832632-eb11-4859-8ffe-33f3bdc36c7c)
2、 如果勾选的目标主机只有IPv6，没有IP，不会传给作业平台执行
![image](https://github.com/TencentBlueKing/bk-sops/assets/120009833/27354df3-baf5-4f90-ad4b-b49a2e6db9f9)
![image](https://github.com/TencentBlueKing/bk-sops/assets/120009833/af3c9145-884b-4a0c-a065-88a96f3490d4)

重现方法
=======

**Comment by hanshuaikang** [comment]
问题原因:

仅default模块打开了 BKAPP_ENABLE_IPV6的开关，pipeline 模块未打开导致的
