### ISSUE TITLE
后台支持设定插件的某个版本为默认版本

### ISSUE THREAD

**Issue by ecoli666** [TencentBlueKing/bk-sops#7187]
关键信息
=======

- [ ] bk-sops 版本：master

问题描述
=======
插件的默认版本，当前规则是按照版本号自动排序，高版本优先。
希望后台可以支持设定插件的某个版本为默认版本

原因
=======
1. 某些版本（比如有非严重问题、某个试验的特性，不希望主推），优先还是推荐低版本

![image](https://github.com/TencentBlueKing/bk-sops/assets/42025090/c9a94de2-bebe-49e1-b16d-982a5eb9f6a1)

**Comment by normal-wls** [comment]
1. bamboo-pipeline更新到3.24.3
2. 集成之后 component 接口会多一个字段，is_default_version，在根据版本号排序完之后遇到的第一个为 true 的就作为默认的版本，如果没有就用最新版本作为默认版本
