### ISSUE TITLE
标准运维-IP选择器，输入条件筛选后点击全选，显示结果不符合预期。

### ISSUE THREAD

**Issue by edehua008** [TencentBlueKing/bk-sops#7190]
产品：标准运维： 3.6.4206
版本：
蓝鲸版本6.0.5
标准运维版本：3.6.4206
问题描述： 问题现象
- 问题现象关键片段（文字）：新增标准运维任务时，选择服务器IP，共4条数据， 筛选后为2条，点击全选，却显示已选择4条，不符合预期结果，预期结果是选中2条。
![image](https://github.com/TencentBlueKing/bk-sops/assets/52396790/91f82b71-50c2-4526-9488-94ed0e3b334b)

尝试过的操作/已经排查过的情况：
尝试将标准运维升级到 3.24.3版本，经验证未解决此问题。

需求：
1. 是否有其他版本解决了此问题？如有版本号是多少？依赖蓝鲸底座哪个版本？
2. 如未有其他版本解决，腾讯规划如何解决此问题？在哪个版本中解决，预计发版日期是什么时候？

**Comment by ecoli666** [comment]
https://github.com/TencentBlueKing/bk-sops/releases/tag/V3.26.15
