### ISSUE TITLE
fix: 【3.32.0】发送通知插件，通知方式icon没有渲染

### ISSUE THREAD

**Issue by MarinPeng** [TencentBlueKing/bk-sops#7304]
关键信息
=======

- [ ] bk-sops 版本：

问题描述
=======

![image](https://github.com/TencentBlueKing/bk-sops/assets/50908315/f98096a9-b9bb-47d0-839e-4424fd8c88a0)

重现方法
=======

**Comment by normal-wls** [comment]
refuse: 对应环境没有配置通知渠道，所以接口无法拉取到数据
